# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
 - job: Job1
   steps:
   - script: echo Job1 - Hello Purnesh!
     displayName: 'Run a one-line script'
   - script:
        echo Add other tasks to build, test, and deploy your project.
        echo Add new line
        echo See https://aka.ms/yaml
     displayName: 'Run a multi-line script'
 - job: Job2
   steps:
   - script: echo Job2 - Hello Purnesh Aloni!
     displayName: 'Run a one-line script'
   - script:
        echo Add other tasks to build, test, and deploy your project.
        echo Add files 
        echo See https://aka.ms/yaml
     displayName: 'Run a multi-line script'
